### ISSUE TITLE
Update installation script with AL2023 and Linux kernel version 6.1 support

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-stack#73]
The [install-elastio.sh](https://github.com/elastio/elastio-stack/blob/master/scripts/install-elastio.sh) should allow to install `elastio` on AL2023 as far as we'll have `elastio` packages and repository for `AL2023`.
Also this script should allow to install `elastio-snap` onto the machines with the Linux kernel 6.1 as far as we'll have this kernel version supported in the driver.

**Comment by i-krasnoshchokov** [comment]
Retested for installing from master branch on AL2023 instance with Linux Kernel 6.1 
Instance id: i-066ea8fdefac941b2
![image](https://github.com/elastio/elastio-snap/assets/58442921/91f43f9b-dd36-472b-b4a2-f681a65bb4e9)

Retesting result: accepted, `elastio` and `elastio-snap`  installed correctly:
```
[ec2-user@ip-172-31-5-211 ~]$ elastio version
Elastio CLI: 0.26.8 (3d91192 2023-05-25 03:33:59)
Account-level stack: 2023-05-24
Region-level stack: 0.26.7
```

![image](https://github.com/elastio/elastio-stack/assets/58442921/e8ba1388-3dd3-46d0-ac6d-fcabe80baf47)

![image](https://github.com/elastio/elastio-stack/assets/58442921/0a951060-3b88-44be-bfd7-591511e7dbfb)
 
```
[ec2-user@ip-172-31-5-211 ~]$ elastio driver status
Driver: ElastioSnap, status: Loaded (version 0.12.2)
```
